### ISSUE TITLE
Add support for `ipaddress` library

### ISSUE THREAD

**Issue by WoLpH** [ipinfo/python#20]
Since the `ipadress` library is part of the core Python libraries, it would be good to include support for it: https://docs.python.org/3/library/ipaddress.html

The current result:
```
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    print(handler.getDetails(ip))
  File "ipinfo/handler.py", line 48, in getDetails
    raw_details = self._requestDetails(ip_address)
  File "ipinfo/handler.py", line 96, in _requestDetails
    url += "/" + ip_address
TypeError: must be str, not IPv4Address
```

**Comment by bartbroere** [comment]
Previous versions of this package returned instances of ``IPv4Address``, but this was removed with version 2.0.0, because it makes JSON serialization harder.

I don't see a reason why the package shouldn't allow **supplying** an instance of an IP address from the ``ipaddress`` module. I could actually use this in my own projects.
