### ISSUE TITLE
vs CODE couldn't find Module 

### ISSUE THREAD

**Issue by p0wrixlo** [ipinfo/python#26]
When I use it in python idle completely work but in Visual Studio Code make this error:
`Module 'ipinfo' has no 'getHandler' memberpylint(no-member)
AttributeError: partially initialized module 'ipinfo' has no attribute 'getHandler' (most likely due to a circular import)
`

**Comment by UmanShahzad** [comment]
Hey @p0wrixlo ! Sorry for the late response on this.

Most likely it's because you have a file named `ipinfo.py` in the folder of your project. See https://stackoverflow.com/questions/59762996/how-to-fix-attributeerrorpartially-initialized-module for an example.

In any case, closing this because it's not specific to the SDK, but rather to your specific project/environment. Please let me know if that's incorrect.
