### ISSUE TITLE
Async/Await unclosed connector 

### ISSUE THREAD

**Issue by e-lepilov** [ipinfo/python#67]
I'm using async call inside class `Map` method `_get_city_center_coord`. 
```
import ipinfo
import folium

class Map:
    def __init__(self, event_coordinate=None, zoom_start=15, popup=None, tooltip=None):
        self.event_coordinate = event_coordinate
        self.zoom_start = zoom_start
        self.popup = popup
        self.tooltip = tooltip

    @staticmethod
    async def _get_city_center_coord():
        handler = ipinfo.getHandlerAsync('ipinfo_access_token')
        details = await handler.getDetails()
        lat, lon = (details.latitude, details.longitude)
        return lat, lon

    async def show_events(self, event_list):
        m = await self._init_map()
        for event in event_list:
            id, popup, lat, long, tooltip = event
            folium.Marker(
                location=list((lat, long)),
                popup=popup,
                tooltip=tooltip,
                icon=folium.Icon(color="red", icon="info-sign")
            ).add_to(m)
        return m

    async def _init_map(self):
        if self.event_coordinate:
            return folium.Map(location=self.event_coordinate, zoom_start=self.zoom_start)
        else:
            return folium.Map(
                location=await self._get_city_center_coord(),
                zoom_start=self.zoom_start
            )
```

And this code used by fastapi framework this way

```
@router.get('/all', response_model=List[EventList])
async def events_list(
        request: Request,
        service: EventsService = Depends(),
        user: User = Depends(UserService.get_authenticated_user_id),
):
    events = await service.get_list()
    events_data = [
        (
            event['id'], event['title'], event['location']['lat'],
            event['location']['long'], event['activity']['name']
        )
        for event in events
    ]
    m = await Map(zoom_start=12).show_events(events_data)
    return templates.TemplateResponse(
        'events.html',
        context={
            'request': request,
            'events': events,
            'm': m._repr_html_(),
            'user': user
        }
        )
```

Everything works fine, IP coordinates are detected and the map is displayed. But in the console I see a warning

```
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f25f9e1e800>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f25f9e2bac0>, 178355.411)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f25f9e1dff0>
```
Is there a way to close the connection after a request has been made? It looks like there is a lack of `async with` syntax implementation

**Comment by UmanShahzad** [comment]
We'll check why there may be a leak there, and also if we can implement `async with`. Thanks for reporting.

**Comment by e-lepilov** [comment]
@UmanShahzad  Hi
Any update perhaps?

**Comment by UmanShahzad** [comment]
@e-lepilov sorry for the delay on this. We're a little packed but hoping to fix it next week.

**Comment by rm-Umar** [comment]
@e-lepilov Thank you for the feedback and sorry for waiting 😅 !
I just checked and we are already using `async with` and closing the session properly in `deinit` method. The SDK is designed so that when you initialize a `handler`, it creates a session and you can use the same handler for all the requests until you close that process. The reason you are getting this warning is that when you access `/all` endpoint it creates an object of `map` that creates a new handler in the same process. We can't close the session manually from our core code as creating a new session for every request is costly and kills the purpose of initializing `handler` at the beginning. 
You can solve your issue by either initializing the `handler` outside of your map class and passing that handler in your method or some better alternatives according to your code.

**Comment by e-lepilov** [comment]
Thank you for your help. I'll try to figure it out on my side.
