### ISSUE TITLE
No such file

### ISSUE THREAD

**Issue by sergeynosov13** [ipinfo/python#85]
[Errno 2] No such file or directory: 'C:\\Users\\FyrekS\\AppData\\Local\\Temp\\_MEI188962\\ipinfo\\countries.json'

I'm builded my python script then I get this error - [Errno 2] No such file or directory: 'C:\\Users\\FyrekS\\AppData\\Local\\Temp\\_MEI188962\\ipinfo\\countries.json'

**Comment by sergeynosov13** [comment]
Idk, running python file-normal, compiling with PyInstaller-this error

**Comment by sergeynosov13** [comment]
Sorry for bad English

**Comment by sergeynosov13** [comment]
I need this for school project in 2 weeks)

**Comment by UmanShahzad** [comment]
@sergeynosov13 this seems to be because you're using `PyInstaller` - it's not including static files like `countries.json` when building a final output.

See https://stackoverflow.com/questions/46474588/pyinstaller-how-to-include-data-files-from-an-external-package-that-was-install for a solution to this.

Let me know if that solves it for you!

**Comment by sergeynosov13** [comment]
Your package searching file in TEMP directory, idk how get his path.

**Comment by UmanShahzad** [comment]
Can you please share more details to help debug? We don't use PyInstaller and don't know anyone except yourself so far that has used it with this SDK, so will need more info to help you out.

**Comment by UmanShahzad** [comment]
We'll be updating this SDK and others to start using in-code data rather than loading from files so this won't happen going forward for any kind of installer or context.

**Comment by UmanShahzad** [comment]
This is now completed. Let me know if the issue pops up again on the latest version, @sergeynosov13 ?
